title: Training
pages: false
files: true
fields:
  title:
    label: Title
    type:  text
  text:
    label: Text
    type:  textarea
  beader:
    label: Hallen- und Freibäder in der Region
    type:  structure
    style: table
    fields:
      title:
        label: Title
        type:  text
      link:
        label: Link
        type: url
      text:
        label: Text
        type:  textarea
      image:
        label: Bild
        type: image
